name: Master
on:
  push:
    branches: [ master ]
jobs:
  build-test-pack-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore
        run: dotnet restore
        continue-on-error: false
      - name: Build
        run: dotnet build --no-restore
        continue-on-error: false
      - name: Test
        run: dotnet test --no-restore
        continue-on-error: false
      - name: Pack
        run: |
          chmod +x ./scripts/pack.sh
          ./scripts/pack.sh
        shell: bash
        continue-on-error: false
      - name: Publish
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          chmod +x ./scripts/publish.sh
          ./scripts/publish.sh
        shell: bash